/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current authenticated user
         * @description Retorna o usuário autenticado.
         */
        get: operations["8367feff40ba10e43187792cad3132c1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CityAreaAddress: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            granularity: "city_area";
            /** @example Brasil */
            countryName?: string;
            /** @example BR */
            country: string;
            /** @example Pernambuco */
            stateName?: string;
            /** @example PE */
            state: string;
            /** @example Recife */
            city: string;
        };
        FullAddress: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            granularity: "full_address";
            /** @example Brasil */
            countryName?: string;
            /** @example BR */
            country: string;
            /** @example Pernambuco */
            stateName?: string;
            /** @example PE */
            state: string;
            /** @example Recife */
            city: string;
            /** @example 10001-1234 */
            postalCode?: string;
            /** @example Rua das Flores */
            street: string;
            /** @example 123 */
            number: string;
            /** @example Centro */
            neighborhood: string;
            /** @example Apto 201 */
            complement?: string | null;
        };
        Address: components["schemas"]["CityAreaAddress"] | components["schemas"]["FullAddress"];
        ContractCategory: {
            /** @example Formatura */
            name: string;
            /** @example formatura */
            slug: string;
        };
        ClientProfileImage: {
            /**
             * Format: uri
             * @example https://.../original.jpg
             */
            original: string;
            /**
             * Format: uri
             * @example https://.../web.jpg
             */
            web: string;
            /**
             * Format: uri
             * @example https://.../thumb.jpg
             */
            thumb: string;
        };
        ClientGuardian: {
            /** @example Maria da Silva */
            name: string;
            /**
             * @example mother
             * @enum {string}
             */
            type: "mother" | "father" | "grandmother" | "grandfather" | "uncle" | "aunt" | "sister" | "brother" | "godmother" | "godfather" | "other";
            /**
             * Format: email
             * @example mae@example.com
             */
            email?: string | null;
            /** @example +55 81 99999-9999 */
            phone?: string | null;
        };
        Client: {
            /** @example 10 */
            id: number;
            /** @example CLI-0001 */
            code?: string;
            /** @example João dos Testes */
            name: string;
            profile: components["schemas"]["ClientProfileImage"];
            /**
             * Format: date
             * @example 2015-03-25
             */
            birthdate?: string | null;
            /** @example +55 81 98888-7777 */
            phone?: string | null;
            /**
             * Format: date-time
             * @example 2025-11-06T12:00:00Z
             */
            createdAt: string;
            address?: components["schemas"]["FullAddress"] | null;
            guardian?: components["schemas"]["ClientGuardian"] | null;
        };
        Contract: {
            /** @example 1 */
            id: number;
            /** @example CONT-0001 */
            code: string;
            /** @example Formatura 3º Ano 2025 */
            title: string;
            /**
             * Format: date-time
             * @example 2025-11-06T12:00:00Z
             */
            createdAt: string;
            category: components["schemas"]["ContractCategory"];
            address: components["schemas"]["CityAreaAddress"];
            graduationDetails?: components["schemas"]["GraduationDetails"] | null;
        };
        EventType: {
            /** @example 3 */
            id: number;
            /** @example Ensaio */
            name: string;
            category: components["schemas"]["ContractCategory"];
        };
        Event: {
            /** @example 12 */
            id: number;
            /** @example 5 */
            contractId: number;
            /**
             * Format: date
             * @example Salão Nobre – 13/12
             */
            title?: string;
            /**
             * Format: date
             * @example 2025-11-06
             */
            eventDate: string;
            /**
             * Format: time
             * @example 14:30
             */
            startTime?: string | null;
            /** @example Cobertura da formatura */
            description?: string | null;
            /**
             * Format: date-time
             * @example 2025-11-06T12:00:00Z
             */
            createdAt: string;
            contract?: components["schemas"]["Contract"] | null;
            /** @example 120 */
            totalImages: number;
            /**
             * @description bytes
             * @example 34567890
             */
            totalSize: number;
            type: components["schemas"]["EventType"];
        };
        GraduationDetails: {
            /**
             * @example university
             * @enum {string}
             */
            type: "university" | "school";
            /** @example Universidade Federal de Pernambuco */
            institutionName: string;
            /** @example UFPE */
            institutionAcronym?: string | null;
            /** @example Turma 2025 */
            className: string;
            /**
             * @example night
             * @enum {string}
             */
            shift: "morning" | "afternoon" | "night" | "full_time";
            /** @example 2025 */
            conclusionYear: number;
            /** @example Sistemas de Informação */
            universityCourse?: string | null;
            /**
             * @example high_school
             * @enum {string|null}
             */
            schoolGradeLevel?: "elementary_school" | "middle_school" | "high_school" | null;
        };
        /** @description Metadados EXIF e técnicos da imagem */
        ImageMeta: {
            camera?: {
                /** @example Canon */
                make?: string;
                /** @example Canon EOS 6D Mark II */
                model?: string;
                /** @example EF85mm f/1.8 USM */
                lens?: string;
                /** @example Adobe Lightroom Classic 14.5 */
                software?: string;
                /** @example 2025-08-03 21:30:33 */
                capturedAt?: string;
            };
            exposure?: {
                /** @example 1 */
                exposureProgram?: string;
                /** @example 1/160 */
                exposureTime?: string;
                /** @example f/2.5 */
                fNumber?: string;
                /** @example 320 */
                iso?: number;
                /** @example 85mm */
                focalLength?: string;
                /** @example 9 */
                flash?: number;
            };
            location?: {
                /** @example -8.3312 */
                latitude?: number;
                /** @example -36.4201 */
                longitude?: number;
            };
            /** @description Metadados adicionais não padronizados */
            other?: Record<string, never>;
        };
        OriginalImageInfo: {
            /** @example IMG_1234 */
            name: string;
            /**
             * @description Tamanho em bytes da imagem original (se houver)
             * @example 2456789
             */
            size: number | null;
            /**
             * @description Largura da imagem original
             * @example 1980
             */
            width: number;
            /**
             * @description Altura da imagem original
             * @example 1080
             */
            height: number;
            /** @example image/jpeg */
            mimeType: string;
        };
        Image: {
            /** @example 01J5Q8V6WZ3QC4FJ0V5E5VQ7R9 */
            id: string;
            /**
             * Format: uri
             * @example https://s3.amazonaws.com/bucket/image.jpg
             */
            url: string;
            /**
             * @description Versão da imagem (ex: original, web, thumb)
             * @example original
             */
            type: string;
            /**
             * @description Tamanho em bytes
             * @example 2456789
             */
            size: number;
            /**
             * @description Largura da imagem
             * @example 1980
             */
            width?: number;
            /**
             * @description Altura da imagem
             * @example 1080
             */
            height?: number;
            /** @example image/jpeg */
            mimeType: string;
            original?: components["schemas"]["OriginalImageInfo"];
            /** @example 2025-11-06 10:15:00 */
            createdAt: string;
            /** @example 2025-11-06 10:20:00 */
            updatedAt: string;
            /**
             * @description Quantidade de clientes detectados na imagem
             * @example 3
             */
            clientsOnImageCount?: number | null;
        };
        User: {
            /** @example 1 */
            id: number;
            /** @example Vinicius */
            name: string;
            /** @example vinicius@example.com */
            email: string;
            /**
             * Format: uri
             * @example https://.../picture.jpg
             */
            picture?: string | null;
            address: components["schemas"]["FullAddress"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "8367feff40ba10e43187792cad3132c1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
        };
    };
}
