FROM php:8.2-fpm-alpine3.19

WORKDIR /var/www

# Camada única para DEV
RUN apk add --no-cache \
        git \
        unzip \
        icu-dev \
        libzip-dev \
        oniguruma-dev \
        zlib-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        libwebp-dev \
        imagemagick-dev \
        linux-headers \
        $PHPIZE_DEPS \
    && pecl install xdebug redis imagick \
    && docker-php-ext-enable xdebug redis imagick \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j"$(nproc)" intl zip pdo_mysql exif gd pcntl \
    # Configurações PHP \
    && { \
        echo "upload_max_filesize=30M"; \
        echo "post_max_size=35M"; \
        echo "memory_limit=512M"; \
    } > /usr/local/etc/php/conf.d/app-size-limits.ini \
    # Configurações Xdebug \
    && { \
        echo "xdebug.mode = debug,develop"; \
        echo "xdebug.start_with_request = yes"; \
        echo "xdebug.client_host = host.docker.internal"; \
        echo "xdebug.client_port = 9003"; \
        echo "xdebug.idekey = DOCKER_XDEBUG"; \
        echo "xdebug.log = /tmp/xdebug-docker.log"; \
    } > /usr/local/etc/php/conf.d/docker-xdebug.ini

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Mantemos root em dev para o entrypoint corrigir permissões de volume host
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE 9000
CMD ["php-fpm"]
