FROM php:8.2-fpm-alpine

# libs e extensões PHP
RUN apk add --no-cache \
        git \
        unzip \
        icu-dev \
        libzip-dev \
        oniguruma-dev \
        zlib-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        libwebp \
        libwebp-dev \
        imagemagick \
        imagemagick-dev \
        $PHPIZE_DEPS \
    && apk add --no-cache linux-headers \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del linux-headers \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j"$(nproc)" intl zip pdo_mysql exif gd pcntl \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

# Configura o PHP (tamanhos de upload / POST e memória)
RUN { \
    echo "upload_max_filesize=30M"; \
    echo "post_max_size=35M"; \
    echo "memory_limit=512M"; \
} > /usr/local/etc/php/conf.d/app-size-limits.ini

# Configura o XDebug
RUN { \
    echo "xdebug.mode = debug,develop"; \
    echo "xdebug.start_with_request = yes"; \
    echo "xdebug.client_host = host.docker.internal"; \
    echo "xdebug.client_port = 9003"; \
    echo "xdebug.idekey = DOCKER_XDEBUG"; \
    echo "xdebug.log = /tmp/xdebug-docker.log"; \
    echo "xdebug.log_level = 7"; \
} > /usr/local/etc/php/conf.d/docker-xdebug.ini

# Desabilita cache para desenvolvimento
RUN { \
    echo "opcache.enable=1"; \
    echo "opcache.revalidate_freq=0"; \
    echo "opcache.validate_timestamps=1"; \
    echo "opcache.max_accelerated_files=10000"; \
    echo "opcache.memory_consumption=192"; \
    echo "opcache.max_wasted_percentage=10"; \
    echo "opcache.interned_strings_buffer=16"; \
} > /usr/local/etc/php/conf.d/docker-opcache.ini

WORKDIR /var/www

ENV TZ=UTC

EXPOSE 9000
CMD ["php-fpm"]
